FROM node:18-alpine

WORKDIR /app

RUN npm install -g react-native-cli

# Placeholder
# Eventually: Copy package.json and install dependencies; Build the Android APK; Output to /build volume
# ... Hopefully at least ;-;

RUN echo "React Native Mobile Client"

CMD ["echo", "APK should be here"]
